#!/usr/bin/env bash
# Copies Paparazzi golden images into docs/screenshots/{phone,wear}/ and
# regenerates docs/screenshots/README.md so they can be browsed on GitHub.
# Run after `./gradlew recordPaparazziDebug`.
set -euo pipefail
cd "$(dirname "$0")/../.."

out=docs/screenshots
rm -rf "$out/phone" "$out/wear"
mkdir -p "$out"

{
  echo "# Screenshots"
  echo
  echo "Generated by Paparazzi (\`./gradlew recordPaparazziDebug\`) and copied by \`tools/screenshots/sync.sh\`."
  echo "Do not edit by hand."
} > "$out/README.md"

for module in phone wear; do
  src="$module/src/test/snapshots/images"
  [[ -d "$src" ]] || continue
  mkdir -p "$out/$module"
  echo -e "\n## $module\n" >> "$out/README.md"
  for f in $(find "$src" -name '*.png' | sort); do
    # com.heartline.wear_EcgScreenshotTest_measuring.png -> EcgScreenshotTest_measuring.png
    # com.heartline.phone_PhoneScreenshotTest_home[dark]_home.png -> home_dark.png
    # com.heartline.wear_WearScreenshotTest_launcher[small]_launcher.png -> launcher_small.png
    name="$(basename "$f" | sed -E -e 's/^[^_]+_[^_]+_[^[]+\[([a-z0-9]+)\]_(.*)\.png$/\2_\1.png/' -e 't' -e 's/^[^_]+_[^_]+_[^_]+_(.*)$/\1/')"
    cp "$f" "$out/$module/$name"
    echo "### ${name%.png}" >> "$out/README.md"
    echo "<img src=\"$module/$name\" width=\"$([[ $module == wear ]] && echo 240 || echo 280)\">" >> "$out/README.md"
    echo >> "$out/README.md"
  done
done
echo "Synced $(find "$out" -name '*.png' | wc -l) screenshots to $out"
